#!/usr/bin/env bash

echo "Linting"

LINTTOTAL=0

for i in *.js
do
  echo "Lint $i"
  jshint --verbose $i
  JSHINTRC=$?
  if [ $JSHINTRC -gt 0 ]
  then
    (( LINTTOTAL = LINTTOTAL + 1 ))
  fi
done

#manual lint
if grep -iH automation *.js *.css *.html
then
  echo "Illegal spelling found"
  (( LINTTOTAL = LINTTOTAL + 1 ))
fi

if [ $LINTTOTAL -gt 0 ]
then
  echo "LINT FAIL"
  exit 1
else
  echo "LINT PASS"
  exit 0
fi
